version: "3.7"
services:
  app:
    build:
      args:
        user: ricardo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: calculator
    container_name: calculator-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - calculator

  db:
    image: mysql:5.7
    container_name: calculator-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
    - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - calculator

  db-test:
    image: mysql:5.7
    container_name: calculator-db-test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${TEST_DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${TEST_DB_PASSWORD}
      MYSQL_PASSWORD: ${TEST_DB_PASSWORD}
      MYSQL_USER: ${TEST_DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
    - ${TEST_DB_PORT}:3306
    networks:
      - calculator

  nginx:
    image: nginx:alpine
    container_name: calculator-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - calculator

networks:
  calculator:
    driver: bridge
